### ISSUE TITLE
cast(value) is not correctly parse

### ISSUE THREAD

**Issue by lublak** [HaxeCheckstyle/haxeparser#63]
cast(value) is currently parsed as ECast(ECheckType(value, null) ,null).
But just should parse to ECast(value, null)

**Comment by Simn** [comment]
Uhm, `parseTypeHint` should not accept in that case. The `case _: null;` should not be there, this is was `parseTypeOpt` is for. Try removing that case and see if everything explodes.

**Comment by lublak** [comment]
@Simn after removing: https://github.com/HaxeCheckstyle/haxeparser/blob/dace004f6aff39cf7cf3a9279da24f63b27de2af/src/haxeparser/HaxeParser.hx#L1030

it works fine
